# Site settings
title: "공대아름"
description: "프론트엔드 관련 기술을 주제로 합니다."
url: "https://kimally.github.io/"
author:
  name: "Ahreum Kim (Ally)"
  email: "kim.ah.rm@gmail.com"
  url: "https://kimally.github.io"


# Build settings
baseurl: / # 주어진 URL 로 웹사이트를 작동시킴
source: . #Jekyll 이 읽어들일 파일들의 경로
destination: ./dist-site # Jekyll 이 생성할 파일들의 경로
permalink: /:year/:month/:day/:title # https://jekyllrb.com/docs/permalinks/#template-variables
paginate: 10 #######
paginate_path: /page:num/ #######
encoding: utf-8


# 특정 디렉토리나 파일을 변환되지 않도록 제외시킨다.
# 지킬에서 빌드되지 않도록하는 폴더를 지정한다
# exclude: [.git, .gitignore, .sass-cache, node_modules]
exclude:
  - .sass-cache
  - .git
  - .gitignore
  - node_modules
  - READMD.md


# Default values
defaults:
  -
    scope:
      path: "" # https://jekyllrb.com/docs/static-files/#add-front-matter-to-static-files
      type: "posts"
    values:
      layout: "post"


# sass는 자동으로 지킬에서 변환한다.
# css  폴더에 main.scss 하고 sass  폴더의 파일을 임포트한다.
# 만약 css 폴더없이 sass 를 변환하고 싶다면 grunt 를 이용해야 한다.
# sass
sass:
  sass_dir: _sass
  style: :compressed


# 코드 하이라이트 설정
# 코드 하이라이트 기능중에 GFM를 사용해서 깃헙사이트와 동일하게 보여준다.
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge


# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap


# Custom variables
version: "1.0.0"
simple_search: http://google.com/search
google_analytics: UA-51196485-2
# twitter_username: 
# github_username: 
# linkedin_username: 
# facebook_username: 
# highlighter: rouge


# Options
custom_header: false
custom_nav_footer: false
reverse: false
